### ISSUE TITLE
No linux arm64 support

### ISSUE THREAD

**Issue by darkoverlordofdata** [nodegui/node#1]
npm install fails on debian 11 (bullseye) with 
```
[K[?25hnpm ERR! code 1
npm ERR! path /home/darko/GitHub/nodegui-starter/node_modules/@nodegui/qode
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Error while setting up Qode:  Error: Error while downloading Qode v16.4.0:https://github.com/nodegui/qodejs/releases/download/v16.4.0-qode/v16.4.0-qode-linux-arm64.tar.gz. Not Found
npm ERR!     at download (/home/darko/GitHub/nodegui-starter/node_modules/@nodegui/qode/src/downloader.js:33:11)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async setupQode (/home/darko/GitHub/nodegui-starter/node_modules/@nodegui/qode/src/setup.js:19:3)
npm ERR!     at async main (/home/darko/GitHub/nodegui-starter/node_modules/@nodegui/qode/install.js:7:5)
```

**Comment by sedwards2009** [comment]
What kind of hardware you people using Debian on which is also ARM64?

**Comment by KaMeHb-UA** [comment]
there is also a PinePhone that might be running something like Manjaro. There is already a binary package for x64 in [AUR](https://aur.archlinux.org/packages/qodejs-bin) and it would be good if there will be also ARM64 support for hardware like PinePhone. This may ease mobile development

**Comment by croche2574** [comment]
Coming back to this b/c i'd like to use this for dev on a debian based smartphone as well
